modLoader="javafml"
loaderVersion="[1,)"
license="MIT"
issueTrackerURL="https://github.com/cff1028/create_schematics_fix/issues"

[[mods]]
modId="schematicsfix"
version="1.0.0"
displayName="Create Bugfix: Schematic Patch"
authors="CFF1028"
logoFile="icon.png"
description='''Fixes Create Mod schematic issues by:
1. Sanitizing NBT components
2. Blocking banned keywords
3. Archiving anomalous schematics'''

[[dependencies.clipboard_patch]]
modId="neoforge"
version="[21.1.170,)"

[[dependencies.clipboard_patch]]
modId="create"
version="[6.0.0,)"